# Generated by Django 2.0.3 on 2018-06-19 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_facebro', '0001_initial'),
        ('app_facebro', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to='auth_facebro.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='timeline',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='status_comment', to='app_facebro.Status'),
            preserve_default=False,
        ),
    ]
