# Generated by Django 2.0.3 on 2018-06-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_facebro', '0003_auto_20180619_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='content',
        ),
    ]
