# Generated by Django 2.0.3 on 2018-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facebro', '0004_auto_20180619_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.TextField(),
        ),
    ]
