# Generated by Django 2.0.3 on 2018-06-20 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_facebro', '0001_initial'),
        ('app_facebro', '0005_auto_20180619_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_following_friend', to='auth_facebro.User'),
            preserve_default=False,
        ),
    ]
