# Generated by Django 2.0.3 on 2018-06-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_facebro', '0006_friend_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='is_follow',
        ),
    ]
