# Generated by Django 2.0.3 on 2018-06-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_facebro', '0001_initial'),
        ('app_facebro', '0007_remove_friend_is_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='auth_facebro.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='app_facebro.Post'),
            preserve_default=False,
        ),
    ]
