# Generated by Django 2.0.3 on 2018-06-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_facebro', '0001_initial'),
        ('app_facebro', '0008_auto_20180620_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='following_post', to='auth_facebro.User'),
            preserve_default=False,
        ),
    ]
